name: Update README

on:
  schedule:
    - cron: '0 */24 * * *' # Update every day
  workflow_dispatch:

jobs:
  recent-activity:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/Checkout@v3
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
